// Ported from localpages@4d43f26 `src/render.mjs` (sha1 489e2019…).
//
// MarkdownIt configuration: GitHub Alerts, anchors, mermaid fences,
// JSON5-as-JS highlighting, image figures, and link rewriting for static export.
//
// FIVE deltas from upstream, each marked DELTA below. Everything else — the
// `highlight` body, `highlightTodoInSvg`, `wrapStandaloneImages`'s figure markup, the
// slugify, the alerts→anchor plugin order, `disable('replacements')`, and the
// whole `link_open` export rewrite including its linkify `bogus` fixup — is verbatim,
// because tests/docs-render-equivalence.test.js diffs this renderer's output against
// HTML generated by upstream localpages itself.

import MarkdownIt from 'markdown-it';
import alerts from 'markdown-it-github-alerts';
import anchor from 'markdown-it-anchor';
// DELTA 1: upstream does `import { renderMermaidSVG } from 'beautiful-mermaid'`.
// beautiful-mermaid is one flat ~1.5MB module that this extension already ships as
// its OWN lazily-injected bundle (src/fabry/mermaidEntry.js → dist/console/mermaid.js),
// so importing it here would drag 1.5MB into console.js. The renderer is injected
// instead; DocView awaits the existing loader before first paint, and the Node-side
// equivalence test injects `renderMermaidSVG` directly (same package, same 1.1.3).
// DELTA 2: upstream imports the whole of `highlight.js`; this is the curated set (D4).
import hljs from './hljs.js';
import docWarnings from './docWarnings.js';

// Upstream's hardcoded mermaid palette — GitHub light. Kept as the DEFAULT so the
// equivalence test reproduces upstream byte-for-byte; the app passes a dark variant
// when the console is dark (D3, the one place this port adds a theme upstream lacks).
export const MERMAID_LIGHT = {
  bg: '#ffffff', fg: '#1f2328', accent: '#0969da',
  muted: '#656d76', surface: '#f6f8fa', border: '#d0d7de',
};
export const MERMAID_DARK = {
  bg: '#0d1117', fg: '#f0f6fc', accent: '#4493f8',
  muted: '#9198a1', surface: '#151b23', border: '#3d444d',
};

// JSON5 fenced blocks (JSON-with-comments) are highlighted with the JS grammar
// so `//` comments render cleanly. Other tags pass through to highlight.js.
function highlight(str: string, lang?: string): string {
  if (!lang || lang === 'mermaid') return ''; // mermaid handled by the fence override
  const effective = lang === 'json5' ? 'javascript' : lang;
  if (hljs.getLanguage(effective)) {
    try {
      const { value } = hljs.highlight(str, { language: effective, ignoreIllegals: true });
      return `<pre><code class="hljs language-${lang}">${value}</code></pre>`;
    } catch { /* fall through */ }
  }
  return '';
}

// Highlight TODO/TBD inside Mermaid SVGs (where <mark> can't reach).
function highlightTodoInSvg(svg: string): string {
  svg = svg.replace(
    '</style>',
    '  .todo-hl { stroke: #ffdd33; stroke-width: 7px; stroke-linejoin: round; paint-order: stroke fill; fill: #1f2328; font-weight: 700; }\n</style>',
  );
  svg = svg.replace(/(>[^<]*?)\b(TODO|TBD)\b/g, '$1<tspan class="todo-hl">$2</tspan>');
  return svg;
}

// Wrap "standalone" images — an image alone in its paragraph — in <figure> with
// the alt text as <figcaption>. Mixed paragraphs are left alone. The alt has
// already been HTML-escaped inside the <img> tag, so it's safe to drop into
// <figcaption>.
// DELTA 4, forced by DELTA 3: upstream matches a bare `<p>`, which stops matching the
// moment the sync-line rule stamps `data-src-line` on the paragraph — so in the LIVE
// pane (the only place syncLines is set) standalone images silently lost their
// <figure>. The paragraph's attributes are carried onto the <figure> so the block
// stays a scroll anchor. With no attributes present the output is character-for-
// character upstream's, which is what keeps the equivalence fixtures passing.
export function wrapStandaloneImages(html: string): string {
  return html.replace(
    /<p(\s[^>]*)?>\s*(<img\b[^>]*?\balt="([^"]*)"[^>]*?>)\s*<\/p>/g,
    (_m: string, pAttrs: string, imgTag: string, alt: string) => {
      const attrs = pAttrs || '';
      return alt
        ? `<figure${attrs}>${imgTag}<figcaption>${alt}</figcaption></figure>`
        : `<figure${attrs}>${imgTag}</figure>`;
    },
  );
}

export function createMarkdownRenderer(
  { mermaid = null, mermaidTheme = MERMAID_LIGHT }:
  { mermaid?: ((text: string, themeOpts?: any) => string) | null; mermaidTheme?: any } = {},
) {
  const md = new MarkdownIt({
    html: true,
    linkify: true,
    typographer: true,
    highlight,
  })
    .use(alerts)
    .use(anchor, {
      permalink: anchor.permalink.linkInsideHeader({
        symbol: '#',
        placement: 'before',
        ariaHidden: true,
        class: 'anchor',
      }),
      slugify: (s) => s.toLowerCase()
        .replace(/[^\w\s-]/g, '')
        .trim()
        .replace(/\s+/g, '-'),
    })
    // DELTA 5 (owner, 2026-08-17): upstream's `<state-label>` plugin is NOT in this
    // pipeline. Section states are a property of the DELIVERABLE, set in the Architect
    // and stored on its Data Storage doc — a deliverable has a stable `_id`, whereas a
    // heading's only identity is a slug derived from its own text, so state held outside
    // the markdown would be orphaned by renaming a heading. What replaces the plugin is a
    // diagnostic: the element (and the near-misses someone would type reaching for it)
    // would otherwise render as nothing at all, silently.
    .use(docWarnings)
    // Disable the typographer "replacements" rule so technical text like "(c)",
    // "(r)", "(tm)" stays literal instead of becoming ©/®/™. Smart quotes (the
    // other half of typographer: true) remain enabled.
    .disable('replacements');

  // DELTA 3: source-line anchors for the split view's editor→preview scroll sync.
  // Runs LAST so it sees the final token stream, and
  // ONLY when env.syncLines is set — the export renders without it, which is what
  // keeps exported HTML byte-identical to upstream's. Mirrors upstream's own
  // env.forExport precedent for env-conditional rendering.
  md.core.ruler.push('sync_lines', (state) => {
    if (!state.env || !state.env.syncLines) return;
    for (const token of state.tokens) {
      // html_block carries raw content and cannot take attributes; tokens without
      // a source map (the injected state-summary) have no line to point at.
      if (token.nesting !== 1 || !token.map || token.type === 'html_block') continue;
      // TOP-LEVEL blocks only (level 0). Stamping nested opens as well — a <li>, or the
      // <p> inside it — produced 8 anchors for 5 blocks, and a nested element resolves
      // `offsetTop` against a different offsetParent than its container does, so the
      // extra anchors would be measured in the wrong coordinate space.
      if (token.level !== 0) continue;
      token.attrSet('data-src-line', String(token.map[0]));
    }
  });

  // Render ```mermaid blocks as inline SVGs via beautiful-mermaid.
  const defaultFence = md.renderer.rules.fence!.bind(md.renderer.rules);
  md.renderer.rules.fence = (tokens, idx, options, env, self) => {
    const token = tokens[idx];
    if (token.info.trim() === 'mermaid' && mermaid) {
      try {
        const svg = highlightTodoInSvg((mermaid as any)(token.content, mermaidTheme));
        // The sync-line attribute rides on the wrapper (the fence renderer bypasses
        // renderToken, so attrSet above cannot reach the emitted markup).
        const line = env && env.syncLines && token.map ? ` data-src-line="${token.map[0]}"` : '';
        return `<div class="wide"${line}>${svg}</div>`;
      } catch (e) {
        console.error('Mermaid render error:', (e as Error).message);
        if (env && Array.isArray(env.mermaidErrors)) env.mermaidErrors.push((e as Error).message);
      }
    }
    return defaultFence(tokens, idx, options, env, self);
  };

  // Rewrite relative `*.md` links to `*.html` for static-export rendering.
  // Invoked via md.render(src, { forExport: true }).
  const defaultLinkOpen = md.renderer.rules.link_open
    || ((tokens, idx, opts, env, self) => self.renderToken(tokens, idx, opts));
  md.renderer.rules.link_open = (tokens, idx, options, env, self) => {
    if (env && env.forExport) {
      const token = tokens[idx];
      const hrefIdx = token.attrIndex('href');
      if (hrefIdx >= 0) {
        let href = token.attrs![hrefIdx][1];
        // linkify auto-converts bare "foo.md" prose into "http://foo.md" anchors
        // (treating .md as a TLD). Detect and rewrite to a same-dir HTML
        // sibling so the bundle's in-doc references resolve.
        const bogus = href.match(/^https?:\/\/([^\/?#]+\.md)(#[^?]*)?$/i);
        if (bogus) href = bogus[1].replace(/\.md$/i, '.html') + (bogus[2] || '');
        const isScheme = /^[a-z][a-z0-9+.-]*:/i.test(href);
        const isRootAbs = href.startsWith('/');
        const isFragment = href.startsWith('#');
        if (!isScheme && !isRootAbs && !isFragment) {
          href = href.replace(/\.md(#[^?]*)?$/i, '.html$1');
        }
        if (href !== token.attrs![hrefIdx][1]) token.attrs![hrefIdx][1] = href;
      }
    }
    return defaultLinkOpen(tokens, idx, options, env, self);
  };

  return md;
}

export { hljs };
