// src/mdh/components/AiInsight.jsx
import { h } from 'preact';
import { useState, useEffect, useRef, useMemo, useCallback } from 'preact/hooks';
import { aiEnabled } from '../store.js';
import * as ai from '../ai.js';

const HELP_SVG = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>';

export function renderInlineMarkdown(text) {
  const parts = [];
  const re = /`([^`]+)`|\*\*([^*]+)\*\*/g;
  let last = 0;
  let match;
  while ((match = re.exec(text)) !== null) {
    if (match.index > last) parts.push(text.slice(last, match.index));
    if (match[1] != null) parts.push(h('code', { class: 'ai-inline-code' }, match[1]));
    else if (match[2] != null) parts.push(h('strong', null, match[2]));
    last = re.lastIndex;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

// mode: 'inline' (horizontal), 'overlay' (absolute positioned in parent's top-right)
export default function AiInsight({ input, type, mode = 'inline' }) {
  const [text, setText] = useState(null);
  const [loading, setLoading] = useState(false);
  const [visible, setVisible] = useState(false);
  const [errMsg, setErrMsg] = useState(null);
  const [popoverPos, setPopoverPos] = useState(null);
  const btnRef = useRef(null);
  const popoverRef = useRef(null);

  const enabled = aiEnabled.value;
  const inputKey = useMemo(
    () => (input != null ? (typeof input === 'string' ? input : JSON.stringify(input)) : null),
    [input],
  );

  // Preload eagerly in background
  useEffect(() => {
    if (!enabled || inputKey == null) { setText(null); return; }
    let cancelled = false;

    (async () => {
      const cached = await ai.getCached(input, type);
      if (cancelled) return;
      if (cached) { setText(cached); return; }

      setText(null);
      setLoading(true);
      setErrMsg(null);
      try {
        const result = await ai.ask(input, type);
        if (!cancelled) setText(result);
      } catch (err) {
        if (!cancelled && err.name !== 'AbortError') setErrMsg(err.message);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => { cancelled = true; };
  }, [enabled, inputKey, type]);

  function updatePos() {
    if (!btnRef.current) return;
    const r = btnRef.current.getBoundingClientRect();
    setPopoverPos({ top: r.bottom + 4, right: window.innerWidth - r.right });
  }

  // Close popover on click outside; reposition on scroll/resize
  useEffect(() => {
    if (!visible || mode !== 'overlay') return;
    function onMouseDown(e) {
      if (btnRef.current?.contains(e.target)) return;
      if (popoverRef.current?.contains(e.target)) return;
      setVisible(false);
    }
    function onScroll() { setVisible(false); }
    document.addEventListener('mousedown', onMouseDown);
    window.addEventListener('scroll', onScroll, true);
    return () => {
      document.removeEventListener('mousedown', onMouseDown);
      window.removeEventListener('scroll', onScroll, true);
    };
  }, [visible, mode]);

  const toggle = useCallback((e) => {
    e.stopPropagation();
    if (!visible) updatePos();
    setVisible((v) => !v);
  }, [visible]);

  if (!enabled || inputKey == null) return null;

  const content = (
    <div class="ai-insight-content">
      {loading && <span class="ai-download-info">Thinking...</span>}
      {text && renderInlineMarkdown(text)}
      {errMsg && <span class="ai-explain-error">{errMsg}</span>}
      {(text || errMsg) && <div class="ai-insight-footer">Generated by AI (Gemini Nano) — may be inaccurate</div>}
    </div>
  );

  const btn = (
    <button
      ref={btnRef}
      class={'ai-insight-btn' + (visible ? ' active' : '') + (text && !loading ? ' ready' : '')}
      title={visible ? 'Hide AI insight' : 'Show AI insight'}
      onClick={toggle}
      dangerouslySetInnerHTML={{ __html: HELP_SVG }}
    />
  );

  if (mode === 'overlay') {
    return (
      <div class="ai-insight-overlay" style={visible ? 'z-index:9999' : ''}>
        {btn}
        {visible && popoverPos && (
          <div
            ref={popoverRef}
            class="ai-insight-popover"
            style={{ position: 'fixed', top: popoverPos.top + 'px', right: popoverPos.right + 'px' }}
          >
            {content}
          </div>
        )}
      </div>
    );
  }

  return (
    <span class="ai-insight-inline">
      {btn}
      {visible && content}
    </span>
  );
}
